@Pays.sql
@adresses.sql
@mutuelles.sql
@specialites.sql
@medecins.sql
@patients.sql
@patientsmedecins.sql
@hopitaux.sql
@services.sql
@hopitauxservices.sql
@groupes.sql
@fabricants.sql
@medicaments.sql
@substances.sql
@allergies.sql
@composition.sql
